### ISSUE TITLE
Is anyone tried class method as computation 

### ISSUE THREAD

**Issue by FutureWeaver** [pgiri/dispy#145]
@pgiri 

Could you help me?
Two question:
Question A:
Last time ,I import dispy ,but dispy_send_file didn't work,I found the import path is in Script.So I tried to remove the file named dispy.py from Script.After that ,I found dispy import path change to Lib\site-packet .Then dispy_send_file worked.I'm confused about that .I installed dispy right?
Question B:
Can I use class method as computation about dispy.JobCluster.I tried and failed.Anyone encountered this question the same with me? 

class A:
    def __init__(self):
        pass

    def test1(self, s):
        s += 1
        return s

    def test(self, a, b, c, key=None):
        import pandas as pd
        s = pd.Series(a)
        s = s + b - c + key
        s = self.test1(s)
        return s

if __name__ == '__main__':
    import dispy
    aa = A()
    cluster = dispy.JobCluster(aa.test, depends=[aa.test1])
    job = cluster.submit([1, 2, 3], 1, 2, key=3)
    if job() is None:
        print(job.exception)
    else:
        print(job())

2018-09-03 17:33:38 pycos - version 4.8.1 with IOCP I/O notifier
2018-09-03 17:33:38 dispy - dispy client version: 4.9.1
2018-09-03 17:33:38 dispy - Storing fault recovery information in "_dispy_20180903173338"
Traceback (most recent call last):
  File "D:/PycharmProjects/dispy_distributed_service/dispy_class_method_test.py", line 24, in <module>
    cluster = dispy.JobCluster(aa.test, depends=[aa.test1])
  File "D:\MyVirtualEnv\dispy_distributed_service\lib\site-packages\dispy\__init__.py", line 2547, in __init__
    lines = inspect.getsourcelines(dep)[0]
  File "D:\python3.5.1_64bit\Lib\inspect.py", line 931, in getsourcelines
    lines, lnum = findsource(object)
  File "D:\python3.5.1_64bit\Lib\inspect.py", line 744, in findsource
    file = getsourcefile(object)
  File "D:\python3.5.1_64bit\Lib\inspect.py", line 660, in getsourcefile
    filename = getfile(object)
  File "D:\python3.5.1_64bit\Lib\inspect.py", line 613, in getfile
    raise TypeError('{!r} is a built-in class'.format(object))
TypeError: <module 'builtins' (built-in)> is a built-in class
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "D:\MyVirtualEnv\dispy_distributed_service\lib\site-packages\dispy\__init__.py", line 2803, in shutdown
    self.close()
  File "D:\MyVirtualEnv\dispy_distributed_service\lib\site-packages\dispy\__init__.py", line 2790, in close
    if self._compute:
AttributeError: 'JobCluster' object has no attribute '_compute'

**Comment by pgiri** [comment]
You can use class method as computation. However, you need to send object (`self` in above case) as first argument to computation (remote Python interpreter doesn't know about objects at the client). As you can guess, each job submission then has to serialize the object and sent to nodes, which then have to deserialize and reconstruct the object. This can get expensive. Where possible, use functions instead of object methods for computation and build objects at the node instead of sending from client.

**Comment by FutureWeaver** [comment]
Thanks to your reply, I will try later.
