### ISSUE TITLE
Can't run sample.py

### ISSUE THREAD

**Issue by Dementiy** [pgiri/dispy#165]
I want to run `dispy` on my local machine before using on multiple nodes, but I can't run correctly `sample.py`:

```
dispynode.py --clean -d -i '127.0.0.1'
2018-12-18 23:03:40 dispynode - dispynode version: 4.10.3, PID: 49710
2018-12-18 23:03:40 dispynode - node IP address 127.0.0.1 seems to be loopback address; this will prevent communication with clients on other machines. 
2018-12-18 23:03:40 dispynode - Files will be saved under "/var/folders/61/zfpb1tr91vd7z8gc4q86lnpw0000gn/T/dispy/node"

    Apparently previous dispynode (PID None) has gone away;
    please check manually and kill process(es) if necessary

2018-12-18 23:03:40 pycos - version 4.8.7 with kqueue I/O notifier
2018-12-18 23:03:40 dispynode - "Dmitrijs-MacBook-Air.local" serving 4 cpus
2018-12-18 23:03:40 dispynode - TCP server at 127.0.0.1:51348

Enter "quit" or "exit" to terminate dispynode,
  "stop" to stop service, "start" to restart service,
  "release" to check and close computation,
  "cpus" to change CPUs used, anything else to get status

2018-12-18 23:03:44 pycos - uncaught exception in !tcp_req/4373121336:
Traceback (most recent call last):
  File "/Users/dementiy/.virtualenvs/test-env/lib/python3.7/site-packages/pycos/__init__.py", line 905, in _async_recv_msg
    raise StopIteration(data)
StopIteration: bytearray(b'PING:\x80\x04\x95\x89\x00\x00\x00\x00\x00\x00\x00}\x94(\x8c\x07version\x94\x8c\x064.10.3\x94\x8c\x04sign\x94\x8c(cb8e83964e07eb817b0a69ee292d1d6478d39c6a\x94\x8c\x04port\x94M\x93\xc8\x8c\x0cnode_ip_addr\x94\x8c\t127.0.0.1\x94\x8c\x08ip_addrs\x94]\x94\x8c\t127.0.0.1\x94au.')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/dementiy/.virtualenvs/test-env/lib/python3.7/site-packages/pycos/__init__.py", line 3665, in _schedule
    retval = task._generator.throw(*exc)
  File "/Users/dementiy/.virtualenvs/test-env/bin/dispynode.py", line 1568, in tcp_req
    msg = yield conn.recv_msg()
  File "/Users/dementiy/.virtualenvs/test-env/lib/python3.7/site-packages/pycos/__init__.py", line 3667, in _schedule
    retval = task._generator.send(task._value)
RuntimeError: generator raised StopIteration
```

Then I ran the `sample.py` and received the following error:

```
2018-12-18 23:03:44 pycos - version 4.8.7 with kqueue I/O notifier
2018-12-18 23:03:44 dispy - dispy client version: 4.10.3
2018-12-18 23:03:44 dispy - Storing fault recovery information in "_dispy_20181218230344"
2018-12-18 23:03:44 pycos - uncaught exception in !tcp_server/4317714568:
Traceback (most recent call last):
  File "/Users/dementiy/.virtualenvs/test-env/lib/python3.7/site-packages/pycos/__init__.py", line 2344, in wait
    raise StopIteration(True)
StopIteration: True

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/dementiy/.virtualenvs/test-env/lib/python3.7/site-packages/pycos/__init__.py", line 3665, in _schedule
    retval = task._generator.throw(*exc)
  File "/Users/dementiy/.virtualenvs/test-env/lib/python3.7/site-packages/dispy/__init__.py", line 998, in tcp_server
    yield port_bound_event.wait()
  File "/Users/dementiy/.virtualenvs/test-env/lib/python3.7/site-packages/pycos/__init__.py", line 3667, in _schedule
    retval = task._generator.send(task._value)
RuntimeError: generator raised StopIteration

2018-12-18 23:03:47 pycos - uncaught exception in !_schedule_jobs/4317714392:
Traceback (most recent call last):
  File "/Users/dementiy/.virtualenvs/test-env/lib/python3.7/site-packages/pycos/__init__.py", line 2359, in wait
    raise StopIteration(True)
StopIteration: True

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/dementiy/.virtualenvs/test-env/lib/python3.7/site-packages/pycos/__init__.py", line 3665, in _schedule
    retval = task._generator.throw(*exc)
  File "/Users/dementiy/.virtualenvs/test-env/lib/python3.7/site-packages/dispy/__init__.py", line 1983, in _schedule_jobs
    yield self._sched_event.wait()
  File "/Users/dementiy/.virtualenvs/test-env/lib/python3.7/site-packages/pycos/__init__.py", line 3667, in _schedule
    retval = task._generator.send(task._value)
RuntimeError: generator raised StopIteration
```

I also tried to use `JobCluster(compute, nodes=['127.0.0.1'], ip_addr=['127.0.0.1'])` instead of `JobCluster(compute)`, but results are the same.

Installed packages:
```
dispy==4.10.3
netifaces==0.10.7
psutil==5.4.7
pycos==4.8.7
```

Sorry if i missed something.

**Comment by pgiri** [comment]
It looks like different Python versions are used for client (Python 3) and dispynode (Python 2).

**Comment by Dementiy** [comment]
On Python3.6 (OS X/Windows) everything works fine.

Errors appear only on version 3.7.0. With `loglevel=dispy.logger.DEBUG` parameter I got exactly the same output.

For your program I got the following output:

```
2018-12-19 21:50:51 pycos - version 4.8.7 with kqueue I/O notifier
2018-12-19 21:50:51 pycos - calling g
2018-12-19 21:50:53 pycos - uncaught exception in !f/4377097496:
Traceback (most recent call last):
  File "test_pycos.py", line 7, in g
    raise StopIteration
StopIteration

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/dementiy/.virtualenvs/test-env/lib/python3.7/site-packages/pycos/__init__.py", line 3665, in _schedule
    retval = task._generator.throw(*exc)
  File "test_pycos.py", line 12, in f
    yield g(event)
  File "/Users/dementiy/.virtualenvs/test-env/lib/python3.7/site-packages/pycos/__init__.py", line 3667, in _schedule
    retval = task._generator.send(task._value)
RuntimeError: generator raised StopIteration
```

**Comment by pgiri** [comment]
Apparently with Python 3.7 `raise StopIteration` in pycos tasks doesn't work (see [PEP 479](https://www.python.org/dev/peps/pep-0479/)). I have a fix for it and will release new versions of pycos and dispy in the next few days.

**Comment by Dementiy** [comment]
Great, thanks. Now everything works fine on both versions of Python (3.6 & 3.7).
