### ISSUE TITLE
Issue Running Canonical Example Program

### ISSUE THREAD

**Issue by adrianvasu** [pgiri/dispy#208]
I am running dispy on a Raspberry Pi 4B+ 2GB RAM
Python Version 3.7.3
dispy Version 4.12.0
pycos Version 4.8.15

Trying to run the Canonical Example Program only difference is I am specifying ip_addr='192.168.2.25' in the jobClusterCreation

On the nodes: sudo dispynode.py -d --clean 

Here is the output to terminal when I run the program on the client

pi@PiServer1:~ $ sudo dispynode.py -d --clean
2020-04-10 20:46:06 dispynode - dispynode version: 4.12.0, PID: 733
2020-04-10 20:46:06 dispynode - Files will be saved under "/tmp/dispy/node"
2020-04-10 20:46:06 pycos - version 4.8.15 with epoll I/O notifier
2020-04-10 20:46:06 dispynode - "PiServer1" serving 4 cpus
2020-04-10 20:46:06 dispynode - TCP server at 192.168.2.29:61591

Enter "quit" or "exit" to terminate dispynode,
  "stop" to stop service, "start" to restart service,
  "release" to check and close computation,
  "cpus" to change CPUs used, anything else to get status: 2020-04-10 20:46:19 dispynode - New computation "20dcb6bcfb8788b5ddd38e8d0bf81c299318ceb2" from 192.168.2.25
2020-04-10 20:46:19 pycos - uncaught exception in !tcp_req/3057098640:
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/pycos/__init__.py", line 3670, in _schedule
    retval = task._generator.throw(*exc)
  File "/usr/local/bin/dispynode.py", line 1718, in tcp_req
    client, resp = yield setup_computation(msg, task=task)
  File "/usr/local/lib/python3.7/dist-packages/pycos/__init__.py", line 3672, in _schedule
    retval = task._generator.send(task._value)
  File "/usr/local/bin/dispynode.py", line 1471, in setup_computation
    compute.setup, globalvars, localvars)
  File "<string>", line 1, in <module>
TypeError: 'NoneType' object is not callable

I have been fighting this for a while now and am not sure what's going on. I have tried using SSL, every combination of JobCluster that I could think of.

Any help would be much appreciated.

**Comment by pgiri** [comment]
This seems to be a bug in 4.12.0! You can try earlier version (e.g., 4.11.1) or wait for next version (will try to release this weekend with this issue fixed).

**Comment by adrianvasu** [comment]
Thank you so much for the quick reply!
