### ISSUE TITLE
uncaught exception in dispynode cleanup computation when cluster is aborted causes nodes to refuse new jobs

### ISSUE THREAD

**Issue by snugglo** [pgiri/dispy#26]
I have a cluster and dispynodes started with --zombie_interval 1
As I kill the cluster the nodes get an uncaught exception
    
    2016-01-20 12:35:51,449 - dispynode - Computation "offline_node" is marked as zombie
    2016-01-20 12:35:51,449 - dispynode - Deleting zombie computation "offline_node"
    2016-01-20 12:35:51,471 - asyncoro - uncaught exception in timer_task/140173755159112:
    Traceback (most recent call last):
    File "/usr/local/lib/python2.7/dist-packages/asyncoro/__init__.py", line 3226, in _schedule
       retval = coro._generator.send(coro._value)
    File "/usr/local/bin/dispynode.py", line 1106, in timer_task
    self.cleanup_computation(compute)
    File "/usr/local/bin/dispynode.py", line 1322, in cleanup_computation
    pickle.dump(compute, fd)
    File "/usr/lib/python2.7/copy_reg.py", line 70, in _reduce_ex
    raise TypeError, "can't pickle %s objects" % base.__name__
    TypeError: can't pickle module objects
and remains unresponsive to new computations.

    2016-01-20 12:37:52,500 - dispynode - Busy (1/1); ignoring ping message from 10.88.116.1:41756

I currently use dispy 4.6.1

**Comment by pgiri** [comment]
With 4.6.4 this shouldn't happen (I hope). The problem is that the computations may create global variables that can't be serialized. When the node decides computation is zombie, it is trying to save all the data in files, but some data can't be serialized. 4.6.4 release doesn't save global variables so it should work. Actually, I am not sure if saving computation on disk is useful at all - if you have issues with 4.6.4, may be it should be fixed.

**Comment by snugglo** [comment]
Thank you for that info and swift reply!
The 4.6.4 indeed solves the problem.
