### ISSUE TITLE
Job is hanging indefinitely

### ISSUE THREAD

**Issue by afillatre** [pgiri/dispy#70]
I'm currently testing your solution to distribute python computation (obviously :)) there are some cases where the job never finishes: looking at the UI, some nodes have received a job to execute, but they're completely hang (proc time isn't incrementing anymore, yet the computation result is never sent back)

As I was unable to pinpoint the problem, or find any usable logs to explain the issue, I created a reproducible test case here: https://github.com/afillatre/dispy-hanging

The job works fine with 1 node only, but when I try having 4 of them, it hangs, depending on the value of `nn` (see code and README.md to see what that means). The higher the `nn` value, the more chances the job will hang.

Your help understanding and resolving the issue will be must appreciated, as this tool looks very promising to us !

**Comment by pgiri** [comment]
You can pass `pulse_interval=10` to `dispy.JobCluster` to get updates from nodes at 10 second intervals. You should then see updates in web browser from the node at that interval. If you don't see updates frequently (e.g., update time), then it is an issue in dispynode.

If you are not in a hurry, I can try your example in a day or two (or over the weekend) and get back to you.

**Comment by afillatre** [comment]
Thanks for your swift reply. Yes, that can wait till monday, though we'll need to decide what tool we'll use pretty soon.

I tried the `pulse_interval` param, like this:
```
dispy.JobCluster(kneighbors_mp, pulse_interval=10)
```
Since I'm pretty new to python, I wonder if this is the right way to do that.
Anyway, I couldn't find additional log with this param, neither on the UI nor on the console.

Also, here is the stacktrace that shows when I ultimately kill the job:

```
2017-03-23 12:26:46 asyncoro - version 4.5.2 with epoll I/O notifier
2017-03-23 12:26:46 dispy - dispy client version: 4.7.3
2017-03-23 12:26:46 dispy - Storing fault recovery information in "_dispy_20170323122646"
2017-03-23 12:26:46 dispy - Started HTTP server at ('0.0.0.0', 8181)
^CTraceback (most recent call last):
  File "knn_map_dispy.py", line 100, in <module>
    host, l = job() # waits for job to finish and returns results
  File "/usr/local/lib/python3.5/dist-packages/dispy/__init__.py", line 121, in __call__
    self.finish.wait()
  File "/usr/lib/python3.5/threading.py", line 549, in wait
    signaled = self._cond.wait(timeout)
  File "/usr/lib/python3.5/threading.py", line 293, in wait
    waiter.acquire()
KeyboardInterrupt
^CError in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 549, in wait
    signaled = self._cond.wait(timeout)
  File "/usr/lib/python3.5/threading.py", line 293, in wait
    waiter.acquire()
KeyboardInterrupt
^CError in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 549, in wait
    signaled = self._cond.wait(timeout)
  File "/usr/lib/python3.5/threading.py", line 293, in wait
    waiter.acquire()
KeyboardInterrupt
```

Hope that helps :)

**Comment by pgiri** [comment]
I just downloaded your test and ran it. It worked fine and finished in 15 seconds. I didn't use docker though.

Interrupting your client program won't kill the jobs on remote node(s). The node(s) will continue to execute the jobs and will abandon interrupted client after a long time (I think default `zombie_interval` is 60 minutes) and until then won't serve any other clients.

I notice that you are building up objects on the client and sending them to node. In this case the data is not large so it is fine, but if you want to use larger data, sending large objects to node (and returning large objects) can be expensive. They will also cause problems with web browser having to show those objects. If possible, send the data (or chunks of data) in `depends` and have the nodes build necessary objects (e.g., you can send whole file to each node and with run each job with an offset and size into that file so the job processes data at that offset and size).

**Comment by afillatre** [comment]
Thanks for this informative comment. I'll try your suggestions out !

However, for now what matters most for me is to be able to understand why the job hangs on my side (i.e. how to find logs, debug it, etc.). This may likely be due to how I handle the data, or the fact that I use Docker, but that's just a wild guess for now.

We're currently deploying the jobs on a virtual python env (i.e. without docker), so we'll be able to test if that works better this way.

**Comment by pgiri** [comment]
At the client (your program) you can get debug log if you pass `loglevel=dispy.logger.DEBUG` to `dispy.JobCluster`. At the node you can get debug log if you pass `-d` option to dispynode.py.

**Comment by afillatre** [comment]
The debug on the the `dispy.JobCluster` is what I was missing. The `-d` on the `dispynode.py` did not seem to do much.

So, using `zombie_interval=5`, my node was able to recover after a failure, given enough time (lines that begin by `##` are my comments):

```
##
## Cluster frozen due to a previous job, but launching a new (smaller) job anyway
##
2017-03-23 13:47:17 asyncoro - version 4.5.2 with epoll I/O notifier
2017-03-23 13:47:17 dispy - dispy client version: 4.7.3
2017-03-23 13:47:17 dispy - dispy client at :51347
2017-03-23 13:47:17 dispy - Storing fault recovery information in "_dispy_20170323134717"
2017-03-23 13:47:17 dispy - Started HTTP server at ('0.0.0.0', 8181)
2017-03-23 13:47:18 dispy - Ignoring pulse message from 172.19.0.4
2017-03-23 13:47:18 dispy - Ignoring pulse message from 172.19.0.2
2017-03-23 13:47:18 dispy - Ignoring pulse message from 172.19.0.3
2017-03-23 13:47:18 dispy - Ignoring pulse message from 172.19.0.5

##
## Got a lot of those a lot for 5 mins (zombie_interval)
##

[...]
2017-03-23 13:51:48 dispy - Ignoring pulse message from 172.19.0.3
2017-03-23 13:51:48 dispy - Ignoring pulse message from 172.19.0.2
2017-03-23 13:51:48 dispy - Ignoring pulse message from 172.19.0.4
2017-03-23 13:51:48 dispy - Ignoring pulse message from 172.19.0.5

##
## Ah, cluster went back to life !
##

2017-03-23 13:51:48 dispy - Discovered 172.19.0.4:51348 (b1cb76f38c3a) with 2 cpus
2017-03-23 13:51:48 dispy - Running job 140156631340400 on 172.19.0.4
2017-03-23 13:51:48 dispy - Running job 140156669918928 on 172.19.0.4
2017-03-23 13:51:48 dispy - Running job 1 / 140156631340400 on 172.19.0.4 (busy: 2 / 2)
2017-03-23 13:51:48 dispy - Running job 0 / 140156669918928 on 172.19.0.4 (busy: 2 / 2)
2017-03-23 13:51:49 dispy - Received reply for job 0 / 140156669918928 from 172.19.0.4
b1cb76f38c3a executed job 0 at 1490277108.485766 with 250
2017-03-23 13:51:49 dispy - Running job 140156631340520 on 172.19.0.4
2017-03-23 13:51:49 dispy - Running job 2 / 140156631340520 on 172.19.0.4 (busy: 2 / 2)
2017-03-23 13:51:49 dispy - Received reply for job 1 / 140156631340400 from 172.19.0.4
b1cb76f38c3a executed job 1 at 1490277108.484893 with 250
2017-03-23 13:51:49 dispy - Running job 140156631340640 on 172.19.0.4
2017-03-23 13:51:49 dispy - Running job 3 / 140156631340640 on 172.19.0.4 (busy: 2 / 2)
2017-03-23 13:51:49 dispy - Received reply for job 2 / 140156631340520 from 172.19.0.4
b1cb76f38c3a executed job 2 at 1490277109.299305 with 250
2017-03-23 13:51:49 dispy - Received reply for job 3 / 140156631340640 from 172.19.0.4
b1cb76f38c3a executed job 3 at 1490277109.3076928 with 250

                           Node |  CPUs |    Jobs |    Sec/Job | Node Time Sec
------------------------------------------------------------------------------
 172.19.0.4 (b1cb76f38c3a)      |     2 |       4 |      0.715 |         2.862

Total job time: 2.862 sec, wall time: 272.165 sec, speedup: 0.011

2017-03-23 13:51:49 dispy - HTTP server waiting for 10 seconds for client updates before quitting

##
## Ah, wait, I got only 1 node back (the one I'm launching the job from). Others are still down
##

2017-03-23 13:51:58 dispy - Ignoring pulse message from 172.19.0.3
2017-03-23 13:51:58 dispy - Ignoring pulse message from 172.19.0.2
2017-03-23 13:51:58 dispy - Ignoring pulse message from 172.19.0.5
2017-03-23 13:51:58 dispy - Discovered 172.19.0.3:51348 (be7eb137dd62) with 2 cpus
2017-03-23 13:52:00 dispy - Closing node 172.19.0.4 for kneighbors_mp / 1490276837777
2017-03-23 13:52:00 dispy - Closing node 172.19.0.3 for kneighbors_mp / 1490276837777
2017-03-23 13:52:00 dispy - Shutting down scheduler ...
2017-03-23 13:52:00 dispy - Scheduler quitting: 0
2017-03-23 13:52:00 dispy - Scheduler quit
2017-03-23 13:52:00 asyncoro - waiting for 1 coroutines to terminate
2017-03-23 13:52:00 dispy - Discovered 172.19.0.3:51348 (be7eb137dd62) with 2 cpus
2017-03-23 13:52:00 asyncoro - terminating Coro ~timer_task/140156636165008 (daemon)
2017-03-23 13:52:00 asyncoro - terminating Coro ~tcp_server/140156636167528 (daemon)
2017-03-23 13:52:00 asyncoro - terminating Coro ~udp_server/140156636165176 (daemon)
2017-03-23 13:52:00 asyncoro - AsynCoro terminated
```

So this is better !

On the second and third launch several minutes later, I only get the node `172.19.0.3` back, the others (`172.19.0.2` and `172.19.0.5`) are still down.

So now I can detect when they're down, but:
* I don't see the reason why
* I'm not sure how to get back the 2 missing nodes

Any idea why ?

**Comment by pgiri** [comment]
Is it likely you have interrupted (with Ctrl-C as you did above) a previous run of your client? The nodes are released by`cluster.close()`. If this is not called and client program terminates abnormally, then nodes will continue to expect client to (re)establish communication to send job results etc. until `zombie_interval` period. Your client program should either release nodes with `cluster.close()` or let the program exit normally (in which case exit handler will close the cluster).

You may want to restart each node with `-d` option (this will show a bit of useful information to diagnose issues).

**Comment by afillatre** [comment]
Thanks for the follow-up.

All nodes are started with the `-d` options, but that didn't output any more information AFAIK.
Testing on a python virtual env, the job is hanging right away. I've got the `loglevel=dispy.logger.DEBUG` option set in the `dispy.JobCluster` call, but I don't get any log either but:

```
(dispy)user@remotemachine:~$ python job.py 
2017-03-24 07:37:24 asyncoro - version 4.5.2 with epoll I/O notifier
2017-03-24 07:37:24 dispy - dispy client version: 4.7.3
2017-03-24 07:37:24 dispy - dispy client at :51347
2017-03-24 07:37:24 dispy - Storing fault recovery information in "_dispy_20170324073724"
2017-03-24 07:37:24 dispy - Started HTTP server at ('0.0.0.0', 8181)
```

The above test is being done with a simple node, started on the same machine the job is being ran from.. This use case was working perfectly on my local docker, so I'm quite lost here.

Regarding the `-d` option, and as I launch the `dispynode` with the `--deamon`. flag, how do I monitor the output (the debug information your talk about) ?

**Comment by pgiri** [comment]
The client discovers nodes with UDP broadcast on port 51348. If that is blocked or UDP packets are being dropped, the client may not find node. Alternately, you can explicitly list the nodes with `nodes` parameter to `JobCluster`, which will use TCP to discover nodes. Note also that if a node is currently tied to another client (or until `zombie_interval` if a client doesn't close), then the node will not ignore new client.

`-d` option to dispynode should give more output. At the least it should give information about clients (trying to) connecting, jobs accepted / finished. If that is not the case, there may be some other issue(s) I can't guess. At least until you get basic examples working, not use daemon mode?
