### ISSUE TITLE
Is dispy testet with windows?

### ISSUE THREAD

**Issue by rddaz2013** [pgiri/dispy#82]
It seems the (PID and IP6) features are not really working on windows env?

**Comment by pgiri** [comment]
IPv6 should work if `netifaces` module is installed. What is PID?

**Comment by rddaz2013** [comment]
(P)rocess ID...

https://stackoverflow.com/questions/550653/cross-platform-way-to-get-pids-by-process-name-in-python

2017-08-11 15:31:41 dispynode - dispynode version: 4.8.2, PID: 1188
2017-08-11 15:31:41 dispynode - node IP address xxxx::xxx:a624:4672:ca12%11 see ms to be loopback address; this will prevent communication with clients on other
 machines.
Traceback (most recent call last):
  File "dispynode.py", line 1918, in <module>
    _dispy_node = _DispyNode(**_dispy_config)
  File "dispynode.py", line 276, in __init__
    config.get('pid', None))
Exception: Another dispynode server seems to be running with PID 4244;
    terminate that process and rerun with "clean" option

**Comment by pgiri** [comment]
It is not clear what about PID is not working then.

It seems there may be another dispynode running or dispynode may have been terminated (killed). You can restart dispynode with "clean" option (e.g., as `dispynode.py --clean`).

dispynode is not able to recognize appropriate IP address to use. You can either indicate correct IP address with `-i` option, or install `netifaces` module.

**Comment by rddaz2013** [comment]
I think the 'tempfile.tempdir' for the config file .. has a problem if it point to path you have no write access to.  

https://github.com/pgiri/dispy/blob/master/py3/dispy/dispynode.py 

Line 266 dest_path_prefix = os.path.join(tempfile.gettempdir(), 'dispy', 'node')

Linux it works
Win7 it works
Win10 tempfile.gettempdir() doesn't work .-(

**Comment by pgiri** [comment]
`tempdir` should be writable. May be you need to configure your system / Python appropriately?

You can also use `dest_path_prefix` option to dispynode to point to a path that is writable.

**Comment by rddaz2013** [comment]
Thx 

dest_path_prefix is a better way...

**Comment by pgiri** [comment]
If the above works, can you comment and close this issue?
