### ISSUE TITLE
Unable to exit/quit or even control-c

### ISSUE THREAD

**Issue by javadba** [pgiri/dispy#83]
I have tried all of those and get the following:

2017-08-15 19:27:10 pycos - uncaught exception in _shutdown/140686503097984:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/pycos/__init__.py", line 3687, in _schedule
    retval = task._generator.send(task._value)
  File "/usr/local/bin/dispynode.py", line 1605, in _shutdown
    sock = AsyncSocket(socket.socket(addrinfo.family, socket.SOCK_STREAM),
AttributeError: 'NoneType' object has no attribute 'family'

This is happening on a client-only node that had not connected succesfully to the scheduler_node

**Comment by javadba** [comment]
There is a follow-up additional problem: it seems that after I killed the process by `kill -9`  there is a residual PID file?  I am unable to restart the dispy:

2017-08-15 19:29:09 dispynode - dispynode version: 4.8.3, PID: 7836
Traceback (most recent call last):
  File "/usr/local/bin/dispynode.py", line 1919, in <module>
    _dispy_node = _DispyNode(**_dispy_config)
  File "/usr/local/bin/dispynode.py", line 274, in __init__
    config.get('pid', None))
Exception: Another dispynode server seems to be running with PID 6285;
    terminate that process and rerun with "clean" option

**Comment by javadba** [comment]
Just to be clear: there is *no* dispy process running: it is a cleanup issue.

  $ ps -ef | grep 6285
(nothing ..)

**Comment by pgiri** [comment]
Client won't terminate with Ctrl-C, as thread is blocked waiting for cluster to finish. One way to terminate is to suspend the program (Ctrl-Z) and kill the process.

A node can be shutdown either by giving "quit" command at dispynode command interface (if it is not running in the background), or by calling `dispynode_shutdown()` in "close" function if the node has been started with `--client_shutdown` option.
