### ISSUE TITLE
Connection errors between 2 machines

### ISSUE THREAD

**Issue by alechko91** [pgiri/dispy#86]
Hi!
I've been working for a while with dispy and it's great.
I have an issue running multiple jobs from a master to a slave.

On the slave, I just run dispy.
On the master, I create a single JobCluster object, and have multiple threads that each of them sends a job and then waits for it to finish.
After a minute or so, I start getting this errors on the master:
`
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\pycos\__init__.py", line 3677, in _schedule
    retval = task._generator.throw(*exc)
  File "C:\Python27\lib\site-packages\dispy\__init__.py", line 1041, in tcp_req
    yield self.file_xfer_process(job_reply, xf, conn, addr)
  File "C:\Python27\lib\site-packages\pycos\__init__.py", line 3677, in _schedule
    retval = task._generator.throw(*exc)
  File "C:\Python27\lib\site-packages\dispy\__init__.py", line 1280, in file_xfer_process
    data = yield sock.recvall(min(xf.stat_buf.st_size-recvd, 1024000))
error: 64
`
(The line numbers might be a bit of because of a few prints I added)

Eventually, after a few of those errors, the master fails completely (probably exit() is called from dispy \ pycos).
I noticed that I get similar errors on the slave:
`
Traceback (most r
ecent call last):
  File "c:\python27\Scripts\dispynode.py", line 832, in xfer_file_req
    yield conn.send_msg(serialize(recvd))
  File "c:\python27\lib\site-packages\pycos\__init__.py", line 3676, in _schedul
e
    retval = task._generator.send(task._value)
  File "c:\python27\lib\site-packages\pycos\__init__.py", line 838, in _async_se
nd_msg
    yield self.sendall(struct.pack('>L', len(data)) + data)
  File "c:\python27\lib\site-packages\pycos\__init__.py", line 1511, in _iocp_se
ndall
    err, n = win32file.WSASend(self._fileno, self._write_result, self._write_ove
rlap, 0)
error: (10054, 'WSASend', 'An existing connection was forcibly closed by the rem
ote host.')
`
I tried to debug it with Wireshark, and I saw indeed that the slave sends a tcp packet with reset.
Another thing I noticed that might be useful, is that when there's only a single thread on the master, it doesn't happen...

Does it have anything to do with the multi-threaded environment? I tried adding a lock to every call that envolved the JobCluster, but the problem remained.
Have you encountered such an issue before?

I'm using python 2.7.

Thanks a lot!

**Comment by pgiri** [comment]
There is no reason to use threads with dispy. There is no benefit with using more than thread (due to Global Interpretter Lock with Python) and likely it is more expensive than using single thread (this may be counter intuitive if you haven't come across issue with GIL). Submitting jobs is short  function that queues the jobs,  so no need to use threads (to improve efficiency). Try it without threads and see if it fixes the issue.
