### ISSUE TITLE
Exception RuntimeError: generator ignored GeneratorExit  (while exiting)

### ISSUE THREAD

**Issue by mettbest** [pgiri/dispy#92]
Sometimes and randomly I get this exception while closing the cluster:

```
2017-11-12 02:00:48 pycos - terminating task !udp_server/140290261409648 (daemon)
2017-11-12 02:00:48 dispy - Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/dispy/__init__.py", line 867, in udp_server
    yield sock.sendall(auth)
GeneratorExit

2017-11-12 02:00:48 pycos - closing udp_server raised exception: Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/pycos/__init__.py", line 3820, in _schedule
    task._generator.close()
RuntimeError: generator ignored GeneratorExit

2017-11-12 02:00:48 pycos - terminating task !tcp_server/140290261409472 (daemon)
2017-11-12 02:00:48 pycos - terminating task !timer_proc/140290261408592 (daemon)
2017-11-12 02:00:48 pycos - pycos terminated
```

**Comment by pgiri** [comment]
This is a harmless warning. Ideally the daemon processes should handle `GeneratorExit` exception and break from the loop, but checking for that each time there are other exceptions can take (tiny bit of) time. As this happens only when program is terminating, it is not a problem.
