### ISSUE TITLE
dispy crashes with error "AttributeError: '_Cluster' object has no attribute 'addrinfo'"

### ISSUE THREAD

**Issue by dismine** [pgiri/dispy#96]
I test dispy with SharedJobCluster and it crashes at the end with error:
```
Traceback (most recent call last):
  File "/home/user/project/env/lib/python3.5/site-packages/pycos/__init__.py", line 3732, in _schedule
    retval = task._generator.send(task._value)
  File "/home/user/project/env/lib/python3.5/site-packages/dispy/__init__.py", line 1472, in del_cluster
    sock = socket.socket(self.addrinfo.family, socket.SOCK_STREAM)
AttributeError: '_Cluster' object has no attribute 'addrinfo'
```

**Comment by dismine** [comment]
Yes, you are right. The line should be replaced to: 
`yield sock.connect((cluster.scheduler_ip_addr, cluster.scheduler_port))`

**Comment by dismine** [comment]
Looks like the same issue in another place:

```
pycos - uncaught exception in !del_cluster/139870558962912:
Traceback (most recent call last):
  File "/home/user/project/env/lib/python3.5/site-packages/pycos/__init__.py", line 3732, in _schedule
    retval = task._generator.send(task._value)
  File "/home/user/project/env/bin/dispy.py", line 1472, in del_cluster
    sock = socket.socket(self.addrinfo.family, socket.SOCK_STREAM)
AttributeError: '_Cluster' object has no attribute 'addrinfo'
```

**Comment by dismine** [comment]
With release 4.8.4 we can close this issue.
